# Generated by Django 5.2 on 2025-04-17 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(default='Default Product Name', max_length=255, primary_key=True, serialize=False)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('name', models.CharField(default='Default Release Name', max_length=255, primary_key=True, serialize=False)),
                ('release_date', models.DateField(default='2023-01-01')),
                ('customers', models.CharField(default='Default Customers', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='http://example.com/image.jpg')),
                ('build_number', models.CharField(default='1234', max_length=100)),
                ('release_date', models.DateTimeField(default='2023-01-01')),
                ('ot2_pass', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('twistlock_report_url', models.URLField(default='http://example.com/report')),
                ('twistlock_report_clean', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('name', models.CharField(default='Default Patch Name', max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(default='Default Description')),
                ('patch_version', models.CharField(default='1.0.0', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('related_products', models.ManyToManyField(related_name='patches_set', to='product_app.product')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='product_app.release')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(default='CVE-1234', max_length=255)),
                ('cvss_score', models.FloatField(default=7.5)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium')], default='High', max_length=50)),
                ('affected_libraries', models.TextField(default='Some Library')),
                ('library_path', models.CharField(blank=True, default='/path/to/library', max_length=500)),
                ('description', models.TextField(default='Security issue description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_issues_set', to='product_app.image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='security_issues',
            field=models.ManyToManyField(blank=True, related_name='images', to='product_app.securityissue'),
        ),
    ]
