# Generated by Django 5.2 on 2025-06-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='twistlock_report_clean',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='twistlock_report_url',
            field=models.URLField(blank=True, default='http://example.com/report', null=True),
        ),
    ]
