# Generated by Django 5.2 on 2025-06-06 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchimage',
            name='helm_charts',
        ),
        migrations.CreateModel(
            name='PatchProductHelmChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helm_charts', models.CharField(blank=True, choices=[('Released', 'Released'), ('Not Released', 'Not Released'), ('Applicable', 'Applicable')], default='Not Released', max_length=15, null=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.patch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
            ],
        ),
    ]
