# Generated by Django 5.2 on 2025-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='registry',
        ),
        migrations.AddField(
            model_name='image',
            name='ot2_pass',
            field=models.BooleanField(default=False),
        ),
    ]
