# Generated by Django 5.2 on 2025-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='release_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
