# Generated by Django 5.2 on 2025-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='patch_state',
            field=models.CharField(choices=[('new', 'New'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='new', max_length=20),
        ),
    ]
