# Generated by Django 5.2 on 2025-05-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patchhighlevelscope',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='patchthirdpartyjar',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='patch',
            name='high_level_scopes',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='third_party_jars',
        ),
        migrations.AddField(
            model_name='patchhighlevelscope',
            name='name',
            field=models.CharField(choices=[('alpine', 'Alpine Linux Base Image'), ('base_os', 'Base OS'), ('tomcat', 'Tomcat'), ('jdk', 'JDK'), ('otds', 'OTDS'), ('otiv', 'OTIV'), ('new_relic', 'New Relic')], default='alpine', max_length=100),
        ),
        migrations.AddField(
            model_name='patchthirdpartyjar',
            name='jar_name',
            field=models.CharField(choices=[('commons-cli', 'commons-cli'), ('commons-codec', 'commons-codec'), ('commons-io', 'commons-io'), ('log4j', 'log4j'), ('spring-core', 'spring framework (spring-core)'), ('spring-security', 'spring security'), ('xmlsec', 'xmlsec'), ('logback-core', 'logback-core'), ('cxf-core', 'Cxf-core'), ('cxf-bindings-soap', 'Cxf-rt-bindings-soap'), ('cxf-bindings-xml', 'Cxf-rt-bindings-xml'), ('cxf-databinding-jaxb', 'Cxf-rt-databinding-jaxb'), ('cxf-frontend-simple', 'Cxf-rt-frontend-simple'), ('cxf-frontend-jaxws', 'Cxf-rt-frontend-jaxws'), ('cxf-transports-http', 'Cxf-rt-transports-http'), ('cxf-ws-addr', 'Cxf-rt-ws-addr'), ('cxf-wsdl', 'Cxf-rt-wsdl'), ('cxf-ws-policy', 'Cxf-rt-ws-policy'), ('freemarker', 'Freemarker Jar'), ('netty-all', 'netty-all'), ('reactor-netty-http', 'reactor-netty-http'), ('reactor-netty-core', 'reactor-netty-core'), ('libraries-bom', 'libraries-bom'), ('httpcore5', 'httpcore5'), ('guava', 'guava'), ('jaxb-api', 'jaxb-api'), ('json', 'json'), ('logback-classic', 'logback-classic'), ('jakarta-mail-api', 'Jakarta.mail-api'), ('spring-boot-parent', 'spring-boot-starter-parent')], default='commons-cli', max_length=100),
        ),
        migrations.AlterField(
            model_name='patch',
            name='client_build_availability',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patch',
            name='code_freeze',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patch',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patch',
            name='kick_off',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patch',
            name='patch_state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patch',
            name='patch_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patch',
            name='platform_qa_build',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patch',
            name='product_images',
            field=models.ManyToManyField(related_name='patches', to='product_app.image'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='related_products',
            field=models.ManyToManyField(related_name='patches', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patchhighlevelscope',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_level_scope_links', to='product_app.patch'),
        ),
        migrations.AlterField(
            model_name='patchthirdpartyjar',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_jar_links', to='product_app.patch'),
        ),
        migrations.RemoveField(
            model_name='patchhighlevelscope',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='patchthirdpartyjar',
            name='jar',
        ),
    ]
