# Generated by Django 5.2 on 2025-06-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_patchimage_helm_charts_patchproducthelmchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='layers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
