# Generated by Django 5.2 on 2025-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_image_registry_image_ot2_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ot2_pass',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
