# Generated by Django 5.2 on 2025-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_patch_patch_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_version',
            field=models.CharField(default='Default version', max_length=50),
        ),
    ]
