# Generated by Django 5.2 on 2025-05-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_image_release_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patchhighlevelscope',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='patchthirdpartyjar',
            unique_together=set(),
        ),
    ]
