# Generated by Django 5.2 on 2025-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_patchhighlevelscope_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='patch_state',
            field=models.CharField(choices=[('new', 'New'), ('rejected', 'Rejected'), ('released', 'Released'), ('verified', 'Verified')], default='New', max_length=20),
        ),
    ]
