# Generated by Django 5.2 on 2025-05-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_image_version_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ot2_pass',
            field=models.CharField(choices=[('Released', 'Released'), ('Not Released', 'Not Released'), ('Applicable', 'Applicable')], default='Not Released', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_name', 'version_name')},
        ),
    ]
