# Generated by Django 5.2 on 2025-05-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_patchhighlevelscope_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='product_images',
            field=models.ManyToManyField(blank=True, related_name='patches', to='product_app.image'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='patches', to='product_app.product'),
        ),
        migrations.AlterUniqueTogether(
            name='patchhighlevelscope',
            unique_together={('patch', 'scope')},
        ),
        migrations.AlterUniqueTogether(
            name='patchthirdpartyjar',
            unique_together={('patch', 'jar')},
        ),
    ]
