# Generated by Django 5.2 on 2025-04-16 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_image_ot2_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='release',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='securityissue',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='patch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='release',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='securityissue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='securityissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
