# Generated by Django 5.2 on 2025-06-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_image_layers_image_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=255)),
                ('registry_registry', models.URLField()),
                ('registry_path', models.CharField(blank=True, max_length=255)),
                ('registry_image_name', models.CharField(max_length=255)),
                ('ot2paas_registry', models.URLField()),
                ('ot2paas_path', models.CharField(blank=True, max_length=255)),
                ('ot2paas_image_name', models.CharField(max_length=255)),
                ('local_registry', models.URLField()),
                ('local_path', models.CharField(blank=True, max_length=255)),
                ('local_image_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('release', 'product', 'image_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductJarRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jar', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.release')),
            ],
            options={
                'unique_together': {('product', 'jar', 'release')},
            },
        ),
    ]
