# Generated by Django 5.2 on 2025-05-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_image_ot2_pass_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
    ]
