# Generated by Django 5.2 on 2025-06-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_releaseproductimage_productjarrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='functional_fixes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='patch',
            name='kba',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='patch',
            name='security_issues',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
