# Generated by Django 5.2 on 2025-05-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_patch_patch_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighLevelScope',
        ),
        migrations.RemoveField(
            model_name='patchhighlevelscope',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='patchthirdpartyjar',
            name='patch',
        ),
        migrations.DeleteModel(
            name='ThirdPartyJar',
        ),
        migrations.AddField(
            model_name='patch',
            name='High_level_state',
            field=models.CharField(choices=[('alpine', 'Alpine Linux Base Image'), ('base_os', 'Base OS'), ('tomcat', 'Tomcat'), ('jdk', 'JDK'), ('otds', 'OTDS'), ('otiv', 'OTIV'), ('new_relic', 'New Relic')], default='alpine', max_length=20),
        ),
        migrations.AddField(
            model_name='patch',
            name='Third_Party_Jars',
            field=models.CharField(choices=[('commons-cli', 'commons-cli'), ('commons-codec', 'commons-codec'), ('commons-io', 'commons-io'), ('log4j', 'log4j'), ('spring-core', 'spring framework (spring-core)'), ('spring-security', 'spring security'), ('xmlsec', 'xmlsec'), ('logback-core', 'logback-core'), ('cxf-core', 'Cxf-core'), ('cxf-bindings-soap', 'Cxf-rt-bindings-soap'), ('cxf-bindings-xml', 'Cxf-rt-bindings-xml'), ('cxf-databinding-jaxb', 'Cxf-rt-databinding-jaxb'), ('cxf-frontend-simple', 'Cxf-rt-frontend-simple'), ('cxf-frontend-jaxws', 'Cxf-rt-frontend-jaxws'), ('cxf-transports-http', 'Cxf-rt-transports-http'), ('cxf-ws-addr', 'Cxf-rt-ws-addr'), ('cxf-wsdl', 'Cxf-rt-wsdl'), ('cxf-ws-policy', 'Cxf-rt-ws-policy'), ('freemarker', 'Freemarker Jar'), ('netty-all', 'netty-all'), ('reactor-netty-http', 'reactor-netty-http'), ('reactor-netty-core', 'reactor-netty-core'), ('libraries-bom', 'libraries-bom'), ('httpcore5', 'httpcore5'), ('guava', 'guava'), ('jaxb-api', 'jaxb-api'), ('json', 'json'), ('logback-classic', 'logback-classic'), ('jakarta-mail-api', 'Jakarta.mail-api'), ('spring-boot-parent', 'spring-boot-starter-parent')], default='log4j', max_length=20),
        ),
        migrations.DeleteModel(
            name='PatchHighLevelScope',
        ),
        migrations.DeleteModel(
            name='PatchThirdPartyJar',
        ),
    ]
