# Generated by Django 5.2 on 2025-05-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_image_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='version_name',
        ),
    ]
