# Generated by Django 5.2 on 2025-05-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_delete_highlevelscope_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='High_level_state',
            new_name='High_level_Scope',
        ),
    ]
