# Generated by Django 5.2 on 2025-05-28 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_remove_image_version_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot2_pass', models.CharField(max_length=10)),
                ('registry', models.URLField(blank=True, null=True)),
                ('helm_charts', models.JSONField(blank=True, null=True)),
                ('patch_build_number', models.CharField(max_length=50)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.image')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.patch')),
            ],
        ),
    ]
