# Generated by Django 5.2 on 2025-06-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_patch_functional_fixes_patch_kba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchImageJar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=False)),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.jar')),
                ('patch_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.patchimage')),
            ],
            options={
                'verbose_name': 'Patch Image Jar',
                'verbose_name_plural': 'Patch Image Jars',
                'unique_together': {('patch_image', 'jar')},
            },
        ),
    ]
