# Generated by Django 5.2 on 2025-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_patchimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchimage',
            name='helm_charts',
            field=models.CharField(blank=True, choices=[('Released', 'Released'), ('Not Released', 'Not Released'), ('Applicable', 'Applicable')], default='Not Released', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patchimage',
            name='ot2_pass',
            field=models.CharField(choices=[('Released', 'Released'), ('Not Released', 'Not Released'), ('Applicable', 'Applicable')], default='Not Released', max_length=15),
        ),
        migrations.AlterField(
            model_name='patchimage',
            name='patch_build_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patchimage',
            name='registry',
            field=models.CharField(blank=True, choices=[('Released', 'Released'), ('Not Released', 'Not Released'), ('Applicable', 'Applicable')], default='Not Released', max_length=15, null=True),
        ),
    ]
