# Generated by Django 5.2 on 2025-06-26 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_patchimagejar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='releaseproductimage',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.release'),
        ),
    ]
