# Generated by Django 5.2 on 2025-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_rename_high_level_state_patch_high_level_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='High_level_Scope',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='Third_Party_Jars',
        ),
        migrations.AddField(
            model_name='patch',
            name='high_level_scope',
            field=models.ManyToManyField(blank=True, limit_choices_to={'name__in': ['alpine', 'base_os', 'tomcat', 'jdk', 'otds', 'otiv', 'new_relic']}, related_name='patches_with_scope', to='product_app.patch'),
        ),
        migrations.AddField(
            model_name='patch',
            name='third_party_jars',
            field=models.ManyToManyField(blank=True, limit_choices_to={'name__in': ['commons-cli', 'commons-codec', 'commons-io', 'log4j', 'spring-core', 'spring-security', 'xmlsec', 'logback-core', 'cxf-core', 'cxf-bindings-soap', 'cxf-bindings-xml', 'cxf-databinding-jaxb', 'cxf-frontend-simple', 'cxf-frontend-jaxws', 'cxf-transports-http', 'cxf-ws-addr', 'cxf-wsdl', 'cxf-ws-policy', 'freemarker', 'netty-all', 'reactor-netty-http', 'reactor-netty-core', 'libraries-bom', 'httpcore5', 'guava', 'jaxb-api', 'json', 'logback-classic', 'jakarta-mail-api', 'spring-boot-parent']}, related_name='patches_with_jar', to='product_app.patch'),
        ),
    ]
