# Generated by Django 5.2 on 2025-07-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_releaseproductimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchimage',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
