# Generated by Django 5.2 on 2025-05-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_patchimage_helm_charts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ot2_pass',
        ),
    ]
