# Generated by Django 5.2 on 2025-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_remove_patch_high_level_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighLevelScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('alpine', 'Alpine Linux Base Image'), ('base_os', 'Base OS'), ('tomcat', 'Tomcat'), ('jdk', 'JDK'), ('otds', 'OTDS'), ('otiv', 'OTIV'), ('new_relic', 'New Relic')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyJar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('commons-cli', 'commons-cli'), ('commons-codec', 'commons-codec'), ('commons-io', 'commons-io'), ('log4j', 'log4j'), ('spring-core', 'spring framework (spring-core)'), ('spring-security', 'spring security'), ('xmlsec', 'xmlsec'), ('logback-core', 'logback-core'), ('cxf-core', 'Cxf-core'), ('cxf-bindings-soap', 'Cxf-rt-bindings-soap'), ('cxf-bindings-xml', 'Cxf-rt-bindings-xml'), ('cxf-databinding-jaxb', 'Cxf-rt-databinding-jaxb'), ('cxf-frontend-simple', 'Cxf-rt-frontend-simple'), ('cxf-frontend-jaxws', 'Cxf-rt-frontend-jaxws'), ('cxf-transports-http', 'Cxf-rt-transports-http'), ('cxf-ws-addr', 'Cxf-rt-ws-addr'), ('cxf-wsdl', 'Cxf-rt-wsdl'), ('cxf-ws-policy', 'Cxf-rt-ws-policy'), ('freemarker', 'Freemarker Jar'), ('netty-all', 'netty-all'), ('reactor-netty-http', 'reactor-netty-http'), ('reactor-netty-core', 'reactor-netty-core'), ('libraries-bom', 'libraries-bom'), ('httpcore5', 'httpcore5'), ('guava', 'guava'), ('jaxb-api', 'jaxb-api'), ('json', 'json'), ('logback-classic', 'logback-classic'), ('jakarta-mail-api', 'Jakarta.mail-api'), ('spring-boot-parent', 'spring-boot-starter-parent')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='patch',
            name='high_level_scope',
            field=models.ManyToManyField(blank=True, related_name='patches', to='product_app.highlevelscope'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='third_party_jars',
            field=models.ManyToManyField(blank=True, related_name='patches', to='product_app.thirdpartyjar'),
        ),
    ]
