# Generated by Django 5.2 on 2025-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_remove_image_ot2_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchjar',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
