# Generated by Django 5.2 on 2025-05-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_highlevelscope_thirdpartyjar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityissue',
            old_name='image',
            new_name='image_name',
        ),
        migrations.AlterField(
            model_name='patch',
            name='third_party_jars',
            field=models.ManyToManyField(blank=True, choices=[('new', 'New'), ('rejected', 'Rejected'), ('released', 'Released'), ('verified', 'Verified')], related_name='patches', to='product_app.thirdpartyjar'),
        ),
    ]
