# Generated by Django 5.2 on 2025-05-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_remove_image_ot2_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSecurityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_security_des', models.TextField(default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
                ('security_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.securityissue')),
            ],
            options={
                'unique_together': {('product', 'security_issue')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='security_issues',
            field=models.ManyToManyField(related_name='products', through='product_app.ProductSecurityIssue', to='product_app.securityissue'),
        ),
    ]
