# Generated by Django 5.2 on 2025-06-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_patchjar_updated'),
        ('product_app', '0009_productsecurityissue_product_security_issues'),
    ]

    operations = [
    ]
