# Generated by Django 5.2 on 2025-06-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_merge_20250602_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchProductJar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=False)),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.jar')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.patch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
            ],
            options={
                'verbose_name': 'Patch Product Jar',
                'verbose_name_plural': 'Patch Product Jars',
                'unique_together': {('patch', 'product', 'jar')},
            },
        ),
    ]
