# Generated by Django 5.2 on 2025-06-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_merge_20250602_1413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securityissue',
            unique_together={('cve_id', 'cvss_score', 'severity', 'affected_libraries')},
        ),
    ]
