# Generated by Django 5.2 on 2025-06-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_alter_securityissue_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsecurityissue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productsecurityissue',
            name='patch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.patch'),
        ),
        migrations.AlterUniqueTogether(
            name='productsecurityissue',
            unique_together={('patch', 'product', 'security_issue')},
        ),
    ]
