# Generated by Django 5.2 on 2025-06-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_patchproductjar'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchjar',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patchproductjar',
            name='current_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patchproductjar',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
