# Generated by Django 5.2 on 2025-06-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_alter_productsecurityissue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsecurityissue',
            name='product_security_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
