# Generated by Django 5.2 on 2025-06-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_patchjar_version_patchproductjar_current_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlevelscope',
            name='version',
        ),
        migrations.RemoveField(
            model_name='jar',
            name='version',
        ),
    ]
