# Generated by Django 5.2 on 2025-06-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_alter_productsecurityissue_product_security_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchimage',
            name='ot2_pass',
            field=models.CharField(blank=True, choices=[('Released', 'Released'), ('Not Released', 'Not Released'), ('Applicable', 'Applicable')], default='Not Released', max_length=15, null=True),
        ),
    ]
