# Generated by Django 5.2 on 2025-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_remove_highlevelscope_version_remove_jar_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchhighlevelscope',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
