# Generated by Django 5.2 on 2025-06-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_alter_patchimage_ot2_pass'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_name', 'build_number')},
        ),
    ]
